// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Room struct {
	ID           int64        `json:"id"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
	Name         string       `json:"name"`
	Slug         string       `json:"slug"`
	Period       int32        `json:"period"`
	StartDate    time.Time    `json:"start_date"`
	EndDate      time.Time    `json:"end_date"`
	Public       bool         `json:"public"`
	TimeschemaID int64        `json:"timeschema_id"`
	Creator      int64        `json:"creator"`
}

type Subject struct {
	ID            int64           `json:"id"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     sql.NullTime    `json:"updated_at"`
	Name          string          `json:"name"`
	DaysAndOrders json.RawMessage `json:"days_and_orders"`
	RoomID        sql.NullInt64   `json:"room_id"`
	Lector        sql.NullString  `json:"lector"`
	Extra         sql.NullString  `json:"extra"`
}

type Timeschema struct {
	ID        int64           `json:"id"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt sql.NullTime    `json:"updated_at"`
	Name      string          `json:"name"`
	Items     json.RawMessage `json:"items"`
}

type User struct {
	ID        int64        `json:"id"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	Email     string       `json:"email"`
	Password  string       `json:"password"`
	Token     string       `json:"token"`
}
