version: '3.3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data:Z
      - ./src/db:/db:Z
    ports:
      - 8003:5432
    

  api:
    build: ./build/goapi
    volumes:
      - ./build/api:/api:Z
    ports:
      - 80:8080
    depends_on:
      - db
    env_file:
      - ./.env

  bot:
    build: ./build/bot
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - ./build/bot:/bot:Z

volumes:
  postgres:
