version: '3.3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data:Z
    ports:
      - 8003:5432
    

  web:
    build: ./src/api
    restart: always
    command: sh -c "python manage.py migrate && python /code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./src/api:/code:Z
    ports:
      - 8002:8000
    depends_on:
      - db
    environment: 
      DEBUG: 'True'
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DJANGO_SETTINGS_MODULE: 'mercury.settings'

  bot:
    build: ./src/bot
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - ./src/bot:/bot:Z

# volumes:
#   postgres: