# Generated by Django 3.1.1 on 2021-02-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='schedule_image',
            field=models.ImageField(null=True, upload_to='schedules'),
        ),
    ]
