# Generated by Django 3.1.1 on 2021-02-28 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_room_schedule_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='schedule_image_thumb',
            field=models.ImageField(null=True, upload_to='schedules'),
        ),
        migrations.AlterField(
            model_name='room',
            name='time_schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='schedule.timeschema'),
        ),
    ]
