# Generated by Django 3.1.1 on 2021-01-31 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_room_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='day',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='order',
        ),
        migrations.AddField(
            model_name='subject',
            name='days_and_orders',
            field=models.TextField(default='[]'),
        ),
    ]
