# Generated by Django 3.1.1 on 2021-02-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20210228_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='schedule_image',
            field=models.ImageField(default='', upload_to='schedules'),
        ),
        migrations.AlterField(
            model_name='room',
            name='schedule_image_thumb',
            field=models.ImageField(default='', upload_to='schedules'),
        ),
    ]
