# Generated by Django 3.1.1 on 2021-03-31 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20210228_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeschema',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
