# Generated by Django 3.1.1 on 2020-09-18 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_room_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='duration',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='starts',
            field=models.TimeField(null=True),
        ),
    ]
